apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: g5zkca4bz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: g5zkca4bz-nodejs 
  name: g5zkca4bz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: g5zkca4bz-nodejs 
